[package]
cjc-version = "1.0.5"
name = "lesson_demo"
description = "Sample Cangjie package for package-to-cli testing: Student and Lesson classes"
version = "1.0.0"
output-type = "executable"
compile-option = "-lstdx.encoding.jsonFFI"

[target.aarch64-apple-darwin.bin-dependencies]
path-option = ["/Users/gloria/.cangjie-sdk/6.0/cangjie/api/lib/stdx"]
